<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="<?php echo $_SERVER['WEB_NAME']; ?>、微信营销、微信代运营、微信定制开发、微信托管、微网站、微商城、微营销" name="Keywords">
	<meta content="<?php echo $_SERVER['WEB_NAME']; ?>，国内领先的微信公众智能服务平台，<?php echo $_SERVER['WEB_NAME']; ?>八大微体系：微菜单、微官网、微会员、微活动、微商城、微推送、微服务、微统计，企业微营销必备。" name="Description">
<!-- 
<link rel="stylesheet" type="text/css" href="index.css" media="all">
<link rel="stylesheet" type="text/css" href="bootstrap_min.css" media="all">
<link rel="stylesheet" type="text/css" href="bootstrap_responsive_min.css" media="all">
<link rel="stylesheet" type="text/css" href="style.css" media="all">
<link rel="stylesheet" type="text/css" href="todc_bootstrap.css" media="all">
<link rel="stylesheet" type="text/css" href="themes.css" media="all">
<link rel="stylesheet" type="text/css" href="inside.css" media="all">
 -->
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/index.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/bootstrap_min.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/bootstrap_responsive_min.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/style.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/todc_bootstrap.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/themes.css" media="all">
<link rel="stylesheet" type="text/css" href="<?php echo $CSS; ?>wm/inside.css" media="all">


<title><?php echo $_SERVER['WEB_NAME']; ?>—国内领先的微信公众服务平台</title><script type="text/javascript">var yyuc_jspath = "/@system/";</script><script type="text/javascript" src="/@system/js/jquery.js"></script><script type="text/javascript" src="/@system/js/yyucadapter.js"></script>
  <link rel="shortcut icon" href="css/guanjia.png">


</head>
<body>
	
    <div id="main">
        <div class="container-fluid">
           <div class="row-fluid">
                <div class="span12">
                    <div class="box">
                        <div class="box-title">
                            <div class="span10">
								<h3><i class="icon-gears"></i>套餐介绍</h3>
							</div>
			           		<div class="span2"><a class="btn" href="Javascript:window.history.go(-1)">返回</a></div>
			           </div>     
					   <div class="box-content">
					   <h4 class="box-title text-info">套餐介绍</h4>
                        <table id="listTable" class="table table-bordered table-hover dataTable table-striped">                    
							  <tbody><tr>
							  <td rowspan="2">套餐功能</td>
							  <td rowspan="2">项目内容</td>
							  <td rowspan="2">试用版</td>
							  <td rowspan="2">标准版</td>
							  <td rowspan="2">钻石版</td>
							  <td colspan="9" style="text-align:center;">行业套餐</td>
							 </tr>
							 <tr>
							  <td>微医疗</td>
							  <td>微酒店</td>
							  <td>微汽车</td>
							  <td>微房产</td>
							  <td>微婚庆</td>
							  <td>微商城</td>
							  <td>微餐饮</td>
							  <td>微旅游</td>
							  <td>微商场</td>
							 </tr>
							
							 <tr>
							  <td rowspan="2">自定义关键字</td>
							  <td>默认设置</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>关注时回复</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							
							 <tr>
							  <td>版权</td>
							  <td>显示<?php echo $_SERVER['WEB_NAME']; ?>版权</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							  <td>有</td>
							 </tr>
							 <tr>
							  <td>自定义菜单</td>
							  <td>支持多级菜单</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 
							
							 <tr>
							  <td rowspan="5">微活动</td>
							  <td>优惠券</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>刮刮卡</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>大转盘</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>幸运机</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>一战到底</td>
							  
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							
							
							 
							 
							  <td rowspan="9">微信会员卡</td>
							  <td>商家设置</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>会员卡设置</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>会员管理</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>充值记录</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>积分策略</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>通知管理</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>特权管理</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 
							 <tr>
							  <td>数据统计</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>门店管理</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>微官网</td>
							   <td>个性官网</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>微吧</td>
							  <td>粉丝留言</td>
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							  <tr>
							  <td>微调研</td>
							  <td>粉丝调研</td>
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>微团购</td>
							  <td>在线团购</td>
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>微投票</td>
							  <td>粉丝投票</td>
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							 <tr>
							  <td>微预约</td>
							  <td>预约系统</td>
							  <td>√</td>
							  <td>×</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							  <td>√</td>
							 </tr>
							
							 <tr>
							  <td>微喜帖</td>
							  <td>喜帖</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>微酒店</td>
							  <td>酒店预定</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							 
							  <td>×</td>
							   <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td rowspan="4">微医疗</td>
							  <td>挂号设置</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>内容设置</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>预约查询</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>预约统计</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td rowspan="7">微汽车</td>
							  <td>品牌管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>车系管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>车型管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>销售管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>预约保养</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>预约试驾</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>实用工具</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td rowspan="6">微房产</td>
							  <td>楼盘简介</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>子楼盘</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 
							 <tr>
							  <td>楼盘户型360度全景展示</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							
							 <tr>
							  <td>楼盘相册</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>房友印象</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>专家点评</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td rowspan="4">微商城</td>
							  <td>商品管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>订单管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>会员管理</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>系统设置</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>微餐饮</td>
							  <td>订餐系统</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>微旅游</td>
							  <td>微旅游</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							  <td>×</td>
							 </tr>
							 <tr>
							  <td>微商场</td>
							  <td>微商场</td>
							  <td>√</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>×</td>
							  <td>√</td>
							 </tr>
							</tbody></table>
                        
                        </div>
						
						
						</div>
						</div>
						</div>
						</div>
						</div>
						</div>
						 <div id="footer">
        <p>
            Copyright (c) 2011-2013 <?php echo $_SERVER['WEB_NAME']; ?> . All Rights Reserved
        </p>
        <a href="" class="gototop"><i class="icon-arrow-up"></i></a>
    	</div>

		<div id="fallr-overlay"></div>
						</body>
						</html>