document.writeln("<style type=\"text/css\">");
document.writeln("body { margin-bottom:60px !important; }");
document.writeln("a, button, input { -webkit-tap-highlight-color:rgba(255, 0, 0, 0); }");
document.writeln("ul, li { list-style:none; margin:0; padding:0 }");
document.writeln(".top_bar { position: fixed; z-index: 900; bottom: 0; left: 0; right: 0; margin: auto; font-family: Helvetica, Tahoma, Arial, Microsoft YaHei, sans-serif; }");
document.writeln(".top_menu { display:-webkit-box; border-top: 1px solid #3D3D46; display: block; width: 100%; background: rgba(255, 255, 255, 0.7); height: 48px; display: -webkit-box; display: box; margin:0; padding:0; -webkit-box-orient: horizontal; background: -webkit-gradient(linear, 0 0, 0 100%, from(#524945), to(#48403c), color-stop(60%, #524945)); box-shadow: 0 1px 0 0 rgba(255, 255, 255, 0.1) inset; }");
document.writeln(".top_bar .top_menu>li { -webkit-box-flex:1; position:relative; text-align:center; }");
document.writeln(".top_menu li:first-child { background:none; }");
document.writeln(".top_bar .top_menu>li>a { height:48px; margin-right: 1px; display:block; text-align:center; color:#FFF; text-decoration:none; text-shadow: 0 1px rgba(0, 0, 0, 0.3); -webkit-box-flex:1; }");
document.writeln(".top_bar .top_menu>li.home { max-width:70px }");
document.writeln(".top_bar .top_menu>li.home a { height: 66px; width: 66px; margin: auto; border-radius: 60px; position: relative; top: -22px; left: 2px; background: url(http://bcs.duapp.com/baeimg/KRRvB8Lure.png) no-repeat center center; background-size: 100% 100%; }");
document.writeln(".top_bar .top_menu>li>a label { overflow:hidden; margin: 0 0 0 0; font-size: 12px; display: block !important; line-height: 18px; text-align: center; }");
document.writeln(".top_bar .top_menu>li>a img { padding: 3px 0 0 0; height: 24px; width: 24px; color: #fff; line-height: 48px; vertical-align:middle; }");
document.writeln(".top_bar li:first-child a { display: block; }");
document.writeln(".menu_font { text-align:left; position:absolute; right:10px; z-index:500; background: -webkit-gradient(linear, 0 0, 0 100%, from(#524945), to(#48403c), color-stop(60%, #524945)); border-radius: 5px; width: 120px; margin-top: 10px; padding: 0; box-shadow: 0 1px 5px rgba(0, 0, 0, 0.3); }");
document.writeln(".menu_font.hidden { display:none; }");
document.writeln(".menu_font { top:inherit !important; bottom:60px; }");
document.writeln(".menu_font li a { height:40px; margin-right: 1px; display:block; text-align:center; color:#FFF; text-decoration:none; text-shadow: 0 1px rgba(0, 0, 0, 0.3); -webkit-box-flex:1; }");
document.writeln(".menu_font li a { text-align: left !important; }");
document.writeln(".top_menu li:last-of-type a { background: none; overflow:hidden; }");
document.writeln(".menu_font:after { top: inherit!important; bottom: -6px; border-color: #48403c rgba(0, 0, 0, 0) rgba(0, 0, 0, 0); border-width: 6px 6px 0; position: absolute; content: \"\"; display: inline-block; width: 0; height: 0; border-style: solid; left: 80%; }");
document.writeln(".menu_font li { border-top: 1px solid rgba(255, 255, 255, 0.1); border-bottom: 1px solid rgba(0, 0, 0, 0.2); }");
document.writeln(".menu_font li:first-of-type { border-top: 0; }");
document.writeln(".menu_font li:last-of-type { border-bottom: 0; }");
document.writeln(".menu_font li a { height: 40px; line-height: 40px !important; position: relative; color: #fff; display: block; width: 100%; text-indent: 10px; white-space: nowrap; text-overflow: ellipsis; overflow: hidden; }");
document.writeln(".menu_font li a img { width: 20px; height:20px; display: inline-block; margin-top:-2px; color: #fff; line-height: 40px; vertical-align:middle; }");
document.writeln(".menu_font>li>a label { padding:3px 0 0 3px; font-size:14px; overflow:hidden; margin: 0; }");
document.writeln("#menu_list0 { right:0; left:10px; }");
document.writeln("#menu_list0:after { left: 20%; }");
document.writeln("#sharemcover { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.7); display: none; z-index: 20000; }");
document.writeln("#sharemcover img { position: fixed; right: 18px; top: 5px; width: 260px; height: 180px; z-index: 20001; border:0; }");
document.writeln(".top_bar .top_menu>li>a:hover, .top_bar .top_menu>li>a:active { background-color:#333; }");
document.writeln(".menu_font li a:hover, .menu_font li a:active { background-color:#333; }");
document.writeln(".menu_font li:first-of-type a { border-radius:5px 5px 0 0; }");
document.writeln(".menu_font li:last-of-type a { border-radius:0 0 5px 5px; }");
document.writeln("#plug-wrap { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0); z-index:800; }");
document.writeln("#cate18 .device {bottom: 49px;}");
document.writeln("#cate18 #indicator {bottom: 240px;}");
document.writeln("#cate19 .device {bottom: 49px;}");
document.writeln("#cate19 #indicator {bottom: 330px;}");
document.writeln("#cate19 .pagination {bottom: 60px;}");
document.writeln("</style>");
document.writeln("<div id=\"sharemcover\" onClick=\"document.getElementById(\'sharemcover\').style.display=\'\';\" style=\" display:none\"><img src=\"http://bcs.duapp.com/baeimg/MgnnofmleM.png\"></div>");
document.writeln("");
document.writeln("<div class=\"top_bar\" style=\"-webkit-transform:translate3d(0,0,0)\">");
document.writeln("  <nav>");
document.writeln("    <ul id=\"top_menu\"  class=\"top_menu\">");document.writeln("    	<li> <a   onClick=\"javascript:displayit(0)\" ><img src=\"http://bcs.duapp.com/baeimg/S0Iy0cOCO2.png\"><label>加盟乐享</label></a>");
document.writeln("        	<ul id=\"menu_list0\" class=\"menu_font\" style=\" display:none\">");document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=onlinebooking&amp;id=650&amp;tid=819&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/PkKvfNmp1f.png\" ><label>在线加盟</label></a></li>");
document.writeln("                <li> <a href=\"tel:18020718254\"><img src=\"http://bcs.duapp.com/baeimg/GckUWhdhPS.png\" ><label>加盟热线1</label></a></li>");
document.writeln("                <li> <a href=\"tel:18020718274\"><img src=\"http://bcs.duapp.com/baeimg/GckUWhdhPS.png\" ><label>加盟热线2</label></a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    	<li> <a   onClick=\"javascript:displayit(1)\" ><img src=\"http://bcs.duapp.com/baeimg/1yW0BWqD4t.png\"><label>功能演示1</label></a>");
document.writeln("        	<ul id=\"menu_list1\" class=\"menu_font\" style=\" display:none\">");document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=Groupbuying-union&amp;id=650&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/kXsI9ITmWF.png\" ><label>微团购</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=hotels&amp;id=650&amp;tid=1&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/2vlpeaC2QG.png\" ><label>微酒店</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=foodmenu&amp;id=650&amp;shopid=1&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/X6ANFi0tf4.png\" ><label>微外卖</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=diancaimenu&amp;id=650&amp;shopid=1&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/6fLDbriHQG.png\" ><label>微点菜</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=WeddingInvitation-index&amp;id=650&amp;tid=6\"><img src=\"http://bcs.duapp.com/baeimg/VhP8W6ZSAe.png\" ><label>微喜帖</label></a></li>");
document.writeln("                <li> <a href=\"http://www.wxapi.cn/?ac=boxl&amp;tid=650\"><img src=\"http://bcs.duapp.com/baeimg/YBmgNvsll2.png\" ><label>音乐盒</label></a></li>");
document.writeln("                <li> <a href=\"http://apisimsim.duapp.com/?ac=heka1&amp;hkid=439\"><img src=\"http://bcs.duapp.com/baeimg/QNTFCk6GqN.png\" ><label>贺卡</label></a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("<li class=\"home\"><a href=\"http://www.apiwx.com/wxapi.php?ac=cate18&tid=650&wxrf=mp.weixin.qq.com\"></a></li>");
document.writeln("    	<li> <a   onClick=\"javascript:displayit(2)\" ><img src=\"http://bcs.duapp.com/baeimg/9ujht5y43X.png\"><label>抽奖活动</label></a>");
document.writeln("        	<ul id=\"menu_list2\" class=\"menu_font\" style=\" display:none\">");document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=acc&amp;id=650&amp;tid=197&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/XZScjRxoQj.png\" ><label>优惠券</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=zp&amp;id=650&amp;tid=101&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/c7kCJoE3ut.png\" ><label>大转盘</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=acw&amp;id=650&amp;tid=2316&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/zC2RX8voiU.png\" ><label>刮刮卡</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=survey-mobile-index&amp;id=650&amp;tid=1&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/JjN1xB2ygQ.png\" ><label>有奖调研</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=voteimg&amp;id=650&amp;tid=38&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/sqqQOqyrp4.png\" ><label>图片投票</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=votetext&amp;id=650&amp;tid=3&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/j8spuZ9dxk.png\" ><label>文字投票</label></a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    	<li> <a   onClick=\"javascript:displayit(3)\" ><img src=\"http://bcs.duapp.com/baeimg/MczZiNz6a5.png\"><label>其他功能</label></a>");
document.writeln("        	<ul id=\"menu_list3\" class=\"menu_font\" style=\" display:none\">");document.writeln("                <li> <a href=\"http://wxapi.cn/wx/wxapi.php?ac=photo&amp;tid=650\"><img src=\"http://bcs.duapp.com/baeimg/7bE1KgQLIF.png\" ><label>3G相册</label></a></li>");
document.writeln("                <li> <a href=\"http://api.map.baidu.com/marker?location=24.472625,118.111033&amp;title=%E5%8E%A6%E9%97%A8%E5%B8%82%E6%80%9D%E6%98%8E%E5%8C%BA%E5%8E%A6%E7%A6%BE%E8%B7%AF837%E5%8F%B7%E6%B1%87%E6%88%90%E5%A4%A7%E5%8E%A6%E4%B8%89%E5%B1%82%E4%B8%89%E8%87%A3%E5%95%86%E5%8A%A1%E4%B8%AD%E5%BF%83039%E5%8F%B7&amp;content=厦门市思明区厦禾路837号汇成大厦三层三臣商务中心039号&amp;output=html\"><img src=\"http://bcs.duapp.com/baeimg/9DQwTF7I7D.png\" ><label>一键导航</label></a></li>");
document.writeln("                <li> <a href=\"http://comment.duapp.com/?openid=&refex=mp.weixin.qq.com&amp;wxid=926fe795f5afb8d610c8e241b3a7e672\"><img src=\"http://bcs.duapp.com/baeimg/WxbqP9gdE3.png\" ><label>留言墙</label></a></li>");
document.writeln("                <li> <a href=\"http://wxapi.cn/?ac=qj&amp;id=650&amp;tid=547\"><img src=\"http://bcs.duapp.com/baeimg/8syOKrS1tW.png\" ><label>360全景</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=cardindex&amp;id=650&amp;tid=9&amp;c=&refex=mp.weixin.qq.com\"><img src=\"http://bcs.duapp.com/baeimg/kTaX3ZnKAy.png\" ><label>会员卡</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/?ac=fans&refex=mp.weixin.qq.com&c=&tid=650\"><img src=\"http://bcs.duapp.com/baeimg/Q6mFd6ZxNf.png\" ><label>会员资料</label></a></li>");
document.writeln("                <li> <a href=\"http://www.apiwx.com/wxapi.php?ac=news1&amp;w=2&amp;tid=58458\"><img src=\"http://bcs.duapp.com/baeimg/4SrbmLazV7.png\" ><label>功能说明</label></a></li>");
document.writeln("                <li> <a href=\"http://demowx.duapp.com/tools/indexdemo.htm\"><img src=\"http://bcs.duapp.com/baeimg/G30n922Lqe.png\" ><label>生活百事通</label></a></li>");
document.writeln("            </ul>");
document.writeln("        </li>");
document.writeln("    </ul>");
document.writeln("  </nav>");
document.writeln("</div>");
document.writeln("<div id=\"plug-wrap\" onClick=\"closeall()\" style=\"display: none;\"></div>");
document.writeln("<script>");
document.writeln("function displayit(n){");
document.writeln("	var count = document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").length;	");
document.writeln("	for(i=0;i<count;i++){");
document.writeln("		if(i==n){");
document.writeln("		 if(document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display==\'none\'){");
document.writeln("			 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display=\'\';");
document.writeln("			 document.getElementById(\"plug-wrap\").style.display=\'\';");
document.writeln("			}else{");
document.writeln("				 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(n).style.display=\'none\';");
document.writeln("				  document.getElementById(\"plug-wrap\").style.display=\'none\';");
document.writeln("			}");
document.writeln("		}else{");
document.writeln("			document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(i).style.display=\'none\';");
document.writeln("		}");
document.writeln("	}");
document.writeln("}");
document.writeln("function closeall(){");
document.writeln("	var count = document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").length;	");
document.writeln("	for(i=0;i<count;i++){");
document.writeln("		 document.getElementById(\"top_menu\").getElementsByTagName(\"ul\").item(i).style.display=\'none\';");
document.writeln("	}");
document.writeln("	 document.getElementById(\"plug-wrap\").style.display=\'none\';");
document.writeln("}");
document.writeln("document.addEventListener(\'WeixinJSBridgeReady\', function onBridgeReady() {");
document.writeln("WeixinJSBridge.call(\'hideToolbar\');");
document.writeln("});");
document.writeln("</script>");