<?php 
$p_name = '系统管理';
$p_ind = 100;
$p_sub = array(
	array(
		'name'=>'OEM设置',
		'file'=>'oem'		
	),
	array(
		'name'=>'员工管理',
		'file'=>'yuangongliebiao'
	),
	array(
			'name'=>'用户权限分配',
			'file'=>'yonghuquanxian'
	),
	array(
		'name'=>'代理权限分配',
		'file'=>'dailiquanxian'
	),
	array(
		'name'=>'员工权限分配',
		'file'=>'yuangongquanxian'
	),
	array(
		'name'=>'特殊权限分配',
		'file'=>'teshuquanxian'
	),
	array(
		'name'=>'用户价格设置',
		'file'=>'yonghujiage'
	),
	array(
		'name'=>'代理折扣设置',
		'file'=>'dailizhekou'
	),
	array(
		'name'=>'域名绑定统一修正',
		'file'=>'updatedomain'
	),
	array(
    	'name'=>'密码修改',
		'file'=>'updatePwd'
	),		
);